# Generated by Django 5.0.7 on 2024-07-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_checker', '0002_ipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
